### ISSUE TITLE
Lưu dữ liệu trong biến?

### ISSUE THREAD

**Issue by hoangvu12** [HoangTran0410/RevealDeletedFBMessages#1]
Lưu dữ liệu trong biến liệu có bị mất không nhỉ? Tôi thì không có kinh nghiệm về extension nên không rõ. Nếu bị mất thì lưu vào chrome storage hay local storage thì tốt hơn chứ nhỉ?

**Comment by HoangTran0410** [comment]
Đã cập nhật phiên bản mới rồi nhé, hiện tại lưu trong localStorage. Phiên bản tiếp theo sẽ lưu trong chrome storage
