### ISSUE TITLE
không lưu thêm tin nhắn mới

### ISSUE THREAD

**Issue by MSteve3** [HoangTran0410/RevealDeletedFBMessages#2]
![image](https://user-images.githubusercontent.com/46162486/168008909-85232111-958c-4420-b95e-66a2ac444305.png)
hiện tại mình đang xài bản được tải trên chrome store. trước đó bản cài đặt qua file cũng bị trường hợp ko lưu tin nhắn mới khiến mình bỏ lỡ mấy cái chat của ae chat trong group :(((

**Comment by HoangTran0410** [comment]
@MSteve3 bên mình hoạt động bình thường, chưa thấy bác nào bị lỗi này, bác thử những cách sau nhé (theo thứ tự, nếu chạy được rồi thì không cần làm các bước sau)
1. tắt trình duyệt -> mở lại
2. đăng xuất fb -> đăng nhập lại
3. mở F12, vào console -> gõ rvdfm_clear() -> Enter
4. gỡ extension -> cài lại

**Comment by MSteve3** [comment]
> @MSteve3 bên mình hoạt động bình thường, chưa thấy bác nào bị lỗi này, bác thử những cách sau nhé (theo thứ tự, nếu chạy được rồi thì không cần làm các bước sau)
> 
> 1. tắt trình duyệt -> mở lại
> 2. đăng xuất fb -> đăng nhập lại
> 3. mở F12, vào console -> gõ rvdfm_clear() -> Enter
> 4. gỡ extension -> cài lại

Bác reply lâu quá extension nó tự fix luôn rồi :v
