### ISSUE TITLE
"OK" button on swal2 lib is not work

### ISSUE THREAD

**Issue by nh4ttruong** [HoangTran0410/RevealDeletedFBMessages#3]
When click "?" icon on popup layout RDFM, a new mask popup is showed which show info of RDFM. Bottom of that popup is "OK" button and when click on it, nothing happen. I think that the JS script or swal2 lib not work or collision something
![issues](https://user-images.githubusercontent.com/61237126/177023500-4f1b7aa5-319c-42d1-9e00-2883c13f8ff6.jpg)

**Comment by HoangTran0410** [comment]
Please update to the lastest version 0.0.3 (12/07/2023).
This popup was removed.
