### ISSUE TITLE
Errors on Chrome Version 112.0.5615.50 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by itsccao** [HoangTran0410/RevealDeletedFBMessages#4]
!['](https://user-images.githubusercontent.com/72246940/231364538-1946b1fe-91d8-439a-a115-70b937556fe7.png)
![screenshot_1681279109](https://user-images.githubusercontent.com/72246940/231364544-a7998efe-654a-45a6-83be-740a69cc32e6.png)

**Comment by HoangTran0410** [comment]
Please update to the lastest version 0.0.3 (12/07/2023).
