### ISSUE TITLE
Plugin không hoạt động trong Fedora 38

### ISSUE THREAD

**Issue by MinatoIsuki** [HoangTran0410/RevealDeletedFBMessages#5]
![image](https://user-images.githubusercontent.com/102457568/234901113-103680c0-00b1-4d31-aa57-7aa0f6b2d9b8.png)
Dù phát hiện tin nhắn, RVDFM không thể lưu vào localStorage.

**Comment by HoangTran0410** [comment]
Phiên bản 0.0.3 ngày 12/07/2023 đã fix lỗi này, bạn cập nhật lên phiên bản mới nhất là chạy được rồi nhé.
